<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Luis-Hernandez.local" ignored="0" name="Default test" tests="9" failures="1" timestamp="14 Jun 2017 21:23:24 GMT" time="232.105" errors="0">
  <testcase name="NUCP49" time="120.873" classname="rivetlogic.automation.baseline.testcases.basetestsuite.samples.AppsAndLinksTestCases"/>
  <testcase name="NUCP173" time="8.562" classname="rivetlogic.automation.baseline.testcases.basetestsuite.samples.AppsAndLinksTestCases"/>
  <testcase name="NUCP174" time="4.361" classname="rivetlogic.automation.baseline.testcases.basetestsuite.samples.AppsAndLinksTestCases"/>
  <testcase name="NUCP178" time="8.518" classname="rivetlogic.automation.baseline.testcases.basetestsuite.samples.AppsAndLinksTestCases"/>
  <testcase name="NUCP179" time="4.356" classname="rivetlogic.automation.baseline.testcases.basetestsuite.samples.AppsAndLinksTestCases"/>
  <testcase name="NUCP53" time="8.545" classname="rivetlogic.automation.baseline.testcases.basetestsuite.samples.AppsAndLinksTestCases"/>
  <testcase name="NUCP54" time="4.329" classname="rivetlogic.automation.baseline.testcases.basetestsuite.samples.AppsAndLinksTestCases"/>
  <testcase name="NUCP56" time="8.509" classname="rivetlogic.automation.baseline.testcases.basetestsuite.samples.AppsAndLinksTestCases"/>
  <testcase name="NUCP57" time="4.318" classname="rivetlogic.automation.baseline.testcases.basetestsuite.samples.AppsAndLinksTestCases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at rivetlogic.automation.baseline.testcases.basetestsuite.samples.AppsAndLinksTestCases.NUCP57(AppsAndLinksTestCases.java:259)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- NUCP57 -->
</testsuite> <!-- Default test -->
